(require '[clojure.string :as str])
(let [code (slurp "test/datachannel/sctp_robustness_test.clj")
      new-code (str/replace code #"(?s)          handle-sctp-packet \#'core/handle-sctp-packet\]"
                 "          handle-sctp-packet (fn [c p]\n                               (when (and p c)\n                                 (let [state-map @(:state c)\n                                       res (@#'core/handle-sctp-packet state-map p (System/currentTimeMillis))\n                                       next-state (:new-state res)\n                                       network-out (:network-out res)\n                                       app-events (:app-events res)]\n                                   (reset! (:state c) next-state)\n                                   (doseq [out network-out] (.offer (:sctp-out c) out))\n                                   (doseq [evt app-events]\n                                     (case (:type evt)\n                                       :on-message (when-let [cb (:on-message c)] (when (and cb @cb) (@cb (:payload evt))))\n                                       :on-data (when-let [cb (:on-data c)] (when (and cb @cb) (@cb (assoc evt :payload (:payload evt) :stream-id (:stream-id evt)))))\n                                       :on-open (when-let [cb (:on-open c)] (when (and cb @cb) (@cb)))\n                                       :on-error (when-let [cb (:on-error c)] (when (and cb @cb) (@cb (:causes evt))))\n                                       :on-close (when-let [cb (:on-close c)] (when (and cb @cb) (@cb)))\n                                       nil)))))]")]
  (let [new-code (-> new-code
                     (str/replace #"\(handle-sctp-packet \(assoc data-packet1 :src-port 5000 :dst-port 5001\) server-conn\)" "(handle-sctp-packet server-conn (assoc data-packet1 :src-port 5000 :dst-port 5001))")
                     (str/replace #"\(handle-sctp-packet \(assoc data-packet2 :src-port 5000 :dst-port 5001\) server-conn\)" "(handle-sctp-packet server-conn (assoc data-packet2 :src-port 5000 :dst-port 5001))")
                     )]
    (spit "test/datachannel/sctp_robustness_test.clj" new-code)))
